[header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    #  Theme change mode
    # theme change mode ("switch", "select")
    themeChangeMode = "select"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "title name in header config"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #  whether to use typeit animation for title name
      typeit = false

[footer]
    enable = true
    #  Custom content (HTML format is supported)
    custom = ''
    #  whether to show Hugo and theme info
    hugo = true
    #  Hosted on (HTML format is supported)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn = ''
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = false
    # Site creation time
    #since = 2019
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Home page config
[home]
    #  amount of RSS pages
    rss = 10
    # Home page profile
    [home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      # Place your avatar file under static or assets directory
      # The filepath is relative to the static or assets directory
      #avatarURL = "/images/avatar.webp"
      # URL the avatar links to
      avatarLinkURL = ""
      #  title shown in home page (HTML format is supported)
      title = "<h1>Welcome</h1>"
      # subtitle shown in home page
      subtitle = ""
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = false
      #  disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      #  replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = true
